version: '3.8'

services:
  bot:
    build: .
    environment:
      BOT_TOKEN: "6425359689:AAFlmH2c6nma0zvVbr4ABCPgRVoQcGS40hk"
      MONGODB_URL: "mongodb://mongodb:27017/node-boilerplate"
    ports:
      - "8543:443"
    volumes:
      - ./main:/app/main
    restart: always
    command: python /app/main/bot.py
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - dbdata6:/data/db
    networks:
      - my-network

volumes:
  dbdata6:

networks:
  my-network:
    driver: bridge
