version: '3.8'

services:
  bot:
    # Use the Dockerfile in the current directory
    build: .
    # Define environment variables for the bot
    environment:
      BOT_TOKEN: "6425359689:AAFlmH2c6nma0zvVbr4ABCPgRVoQcGS40hk"
    # Map the bot's exposed port to the host's port
    ports:
      - "8443:443"
    # Restart the container automatically in case of failure
    restart: always
